doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: xml
                dir: '%desksheet.modules_dir%/User/Resources/config/doctrine'
                prefix: Desksheet\Module\User\Model
                alias: User
            Expense:
                is_bundle: false
                type: xml
                dir: '%desksheet.modules_dir%/Expense/Resources/config/doctrine'
                prefix: Desksheet\Module\Expense\Model
                alias: Expense
